minix-3.1.2

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -1,70 +1,25 @@
 # /etc/rc - System startup script run by init before going multiuser.
 
-exec >/dev/log
-exec 2>/dev/log
-exec </dev/null
-
 umask 022
-
-# Same settings as in the default /etc/profile. We do not source this file
-# as the system administrator may decide to change those values for his users.
-RC_TZ=/etc/rc.timezone
-PATH=/usr/local/sbin:/usr/pkg/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/pkg/bin:/usr/bin:/bin
-
-# Set TERM to minix if not present.
 TERM="${TERM-minix}"
-
+PATH=/usr/local/bin:/bin:/usr/bin:/usr/sbin
+RC_TZ=/etc/rc.timezone
 export TERM PATH
-
-# Local variables
-ARCH="`sysenv arch`"
 
 usage()
 {
-    echo >&2 "Usage: $0 [-saf] autoboot|start|stop|down"
+    echo >&2 "Usage: $0 [-saf] start|stop|down"
     exec intr sh
 }
 
 up()
 {
+    service=$1
+    shift
+
     # Function to dynamically start a system service
-    opt=""
-    prefix=$(expr "$1 " : '\(-\)')
-    if [ "$prefix" = "-" ];
-    then
-         opt=$1
-         shift
-    fi
-    service=$1
-    shift
-
-    service $opt up /service/$service "$@"
-}
-
-edit()
-{
-    # Function to dynamically edit system service settings
-    opt=""
-    prefix=$(expr "$1 " : '\(-\)')
-    if [ "$prefix" = "-" ];
-    then
-         opt=$1
-         shift
-    fi
-    service=$1
-    shift
-
-    # Assume binaries are always in /service or /usr/pkg/service
-    binlocation=/service/$service
-    if [ ! -x $binlocation ]
-    then	binlocation=/usr/pkg/service/$service
-    fi
-
-    # Mostly to find init...
-    if [ ! -x $binlocation ]
-    then	binlocation=/sbin/$service
-    fi
-    service $opt edit $binlocation -label $service "$@" 
+    echo -n " $service"
+    service up /sbin/$service "$@"
 }
 
 while getopts 'saf' opt
@@ -72,36 +27,30 @@ do
     case $opt in
     s)	sflag=t ;;	# Single user
     a)	aflag=t ;;	# Ask for /usr
-    f)	fflag=-f ;;	# Force a full file system check
+    f)	fflag=t ;;	# Force a full file system check
     *)	usage
     esac
 done
 shift `expr $OPTIND - 1`
 
 case "$#:$1" in
-1:start|1:stop|1:down|1:autoboot)
+1:start|1:stop|1:down)
     action=$1
     ;;
 *)  usage
 esac
 
 case $action in
-autoboot|start)
+start)
+    echo ""
+    echo -n "Multiuser startup in progress ...:"
 
     # National keyboard?
     test -f /etc/keymap && loadkeys /etc/keymap
 
-    # options for fsck. default is -r, which prompts the user for repairs.
-    optname=fsckopts
-    fsckopts=-p
-    if sysenv $optname >/dev/null
-    then       fsckopts="`sysenv $optname`"
-    fi
-
-    if [ "`sysenv debug_fkeys`" != 0 ]
-    then
-        up -n is -period 5HZ
-    fi
+    up is -period 5HZ
+    up cmos -dev /dev/cmos -period 5HZ
+    echo .
 
     # Set timezone.
     export TZ=GMT0
@@ -109,65 +58,95 @@ autoboot|start)
     then . "$RC_TZ"
     fi
 
-    # Start real time clock driver & set system time, otherwise default date.
-    up readclock.drv
-    readclock -q || date 201301010000
-
-    # We are not shutting down.
-    rm -f /etc/nologin
+    # Try to read the hardware real-time clock, otherwise do it manually.
+    readclock || intr date -q
 
     # Initialize files.
-    >/var/run/utmp				# /etc/utmp keeps track of logins
-    >/var/run/utmpx				# /etc/utmpx keeps track of logins
+    printroot >/etc/mtab		# /etc/mtab keeps track of mounts
+    >/etc/utmp				# /etc/utmp keeps track of logins
 
-    # Use MFS binary only from kernel image?
-    if [ "`sysenv bin_img`" = 1 ]
-    then
-        bin_img="-i "
-    fi
+    # /etc/fstab lists the root, tmp and usr devices.
+    . /etc/fstab
+
+    # Any swapspace on a device?
+    test "$swap" : '/dev/' && mount -s $swap
 
     # Are we booting from CD?
     bootcd="`/bin/sysenv bootcd`"
 
-    # If booting from CD, mounting is a special case.
-    # We know what to do - only /usr is mounted and it's readonly.
+    # If booting from CD, /usr has to be mounted readonly.
+    # Also, $usr won't be specified correctly in the
+    # fstab (the CD could be anywhere), so we decide
+    # where it is based on sysenv (set by FS when probing for CD).
     if [ "$bootcd" = 1 ]
-    then	usrdev="$cddev"p2
-    		echo "/usr on cd is $usrdev"
-		mount -r $usrdev /usr
-    else	
-    # If we're not booting from CD, fsck + mount using /etc/fstab.
-		fsck -x / $fflag $fsckopts
-		mount -a
+    then	
+    		#imagedev="`/bin/sysenv cdproberoot`"
+    		#usrdev="`expr $imagedev + 1`"
+    		usr_roflag="-r"
+    		usr="$cddev"p2
+    		echo "Setting /usr on cd is $usr"
     fi
-
-    # Unmount and free now defunct ramdisk
-    umount /dev/imgrd > /dev/null || echo "Failed to unmount boot ramdisk"
-    ramdisk 0 /dev/imgrd || echo "Failed to free boot ramdisk"
-
-    # Edit settings for boot system services
-    if [ "`sysenv skip_boot_config`" != 1 ]
+ 
+    # Mount the /usr partition unless this is a single floppy Minix.
+    if [ ! -d /usr/bin ]
     then
-	edit rs
-	edit vm
-	edit pm
-	edit sched
-	edit vfs
-	edit ds
-	edit tty
-	edit memory
-	edit pfs
-	edit init
+	if [ "$aflag" -o "$usr" = unknown ]
+	then
+	    # We need to ask what the /usr du jour is.
+	    intr sh -c '
+		echo -n "Finish the name of device to mount as /usr: /dev/"
+		read usr
+		echo "usr=/dev/$usr" >/tmp/usr'
+	    . /tmp/usr
+	fi
+	mount $usr_roflag $usr /usr || {
+	    echo "\
+Please try to mount something else as /usr, then hit CTRL-D to continue startup.
+Mount $usr /usr failed -- Single user."
+	    intr sh
+	}
+	rm -f /tmp/usr
     fi
+
+    # Check if the system crashed.
+    if shutdown -C
+    then
+	echo
+	echo "The system was not properly shut down.  Checking file systems."
+	fflag=t
+    fi
+
+    if [ "$fflag" ]
+    then
+	umount $usr
+	echo "fsck / - $root"
+	intr fsck -r $root
+	echo "fsck /usr - $usr"
+	intr fsck -r $usr
+	if [ ! -z "$home" ]
+	then	echo "fsck /home - $home"
+		intr fsck -r $home
+	fi
+	mount $usr /usr
+    fi
+
+    if [ ! -z "$home" ]
+    then mount $home /home || echo "WARNING: couldn't mount $home on /home"
+    fi
+
+    # This file is necessary for above 'shutdown -C' check.
+    # (Silence stderr in case of running from cd.)
+    touch /usr/adm/wtmp 2>/dev/null
 
     if [ "$sflag" ]
     then
-	echo "Single user. Press ^D to resume multiuser startup."
+	echo "Single user."
 	intr sh
-	echo
     fi
 
-    echo "Multiuser startup in progress ..."
+    # Any swapspace on a file?
+    test -n "$swap" -a ! "$swap" : '/dev/' && mount -s $swap
+
 
     case "`printroot -r`":$bootcd in
     /dev/ram:)
@@ -178,38 +157,10 @@ autoboot|start)
 	cp /usr/lib/em* /usr/lib/cpp* /lib
     esac
 
-    echo -n "Starting hotplugging infrastructure... "
-    rm -f /var/run/devmand.pid
-    devmand -d /etc/devmand -d /usr/pkg/etc/devmand &
-    echo "done."
-
     # Things should be alright now.
     ;;
 down|stop)
     sync
-    if [ -f /var/run/devmand.pid ]
-    then
-	kill -INT `cat /var/run/devmand.pid`
-	# without this delay the following will 
-	# be printed in the console
-	# RS: devman not running?
-	sleep 1
-    fi
-    #
-    # usbd needs to be stopped exactly 
-    # at this stage(before stopping devman
-    # and after stopping the services
-    # stated by devmand)
-    if [ -x /usr/pkg/etc/rc.d/usbd ]
-    then 
-	/usr/pkg/etc/rc.d/usbd stop
-    fi
-
-    if [ -x /service/usbd ]
-    then
-	service down usbd
-    fi
-
     # Tell RS server we're going down.
     service shutdown
     ;;
@@ -218,12 +169,9 @@ esac
 # Further initialization.
 test -f /usr/etc/rc && sh /usr/etc/rc $action
 test -f /usr/local/etc/rc && sh /usr/local/etc/rc $action
+test -f /etc/rc.rescue && sh /etc/rc.rescue $action
 
 # Any messages?
-if [ "$action" = start -o "$action" = autoboot ]
-then	if [ -f /etc/issue ]
-	then	cat /etc/issue
-	fi
-fi
+test "$action" = start -a -f /etc/issue && cat /etc/issue
 
 exit 0
diff --git a/etc/usr/rc b/etc/usr/rc
--- a/etc/usr/rc
+++ b/etc/usr/rc
@@ -3,35 +3,11 @@
 RANDOM_FILE=/usr/adm/random.dat
 LOCAL_FILE=/usr/etc/rc.local
 
-ARCH="`sysenv arch`"
-
-if [ ! "$ARCH" ]
-then    # Older kernels do not provide an arch sysenv variable.
-        # We assume we are on x86 then, as existing systems with
-        # kernel and userland (i.e. this script) unsynchronized
-        # will be x86.
-        ARCH=i386
-fi
-
-# Get $SERVICES_DIRS
-. /etc/rc.conf
-
-# Directories to find services in
-if [ ! "$SERVICES_DIRS" ]
-then	SERVICES_DIRS=/service
-fi
-
-# Booting from cd?
-bootcd="`/bin/sysenv bootcd`"
-
 case "$#:$1" in
-1:autoboot)
-    action=start
-    ;;
 1:start|1:stop|1:down)
     action=$1
     ;;
-*)  echo >&2 "Usage: $0 autoboot|start|stop|down"
+*)  echo >&2 "Usage: $0 start|stop|down"
     exit 1
 esac
 
@@ -78,99 +54,33 @@ daemonize()
 
 up()
 {
-    # Function to dynamically start a system service
-    opt=""
-    prefix=$(expr "$1 " : '\(-\)')
-    if [ "$prefix" = "-" ];
-    then
-         opt=$1
-         shift
-    fi
     service=$1
     shift
+
+    # Function to dynamically start a system service
 
     # First check if this service is disabled at the boot monitor.
     if disabled $service; then return; fi
 
     # Service is not disabled. Try to bring it up.
-    found=""
-    for dir in $SERVICES_DIRS
-    do	bin=$dir/$service
-	if [ -x $bin -a -z "$found" ]
-	then	service $opt up $bin "$@" 
-    		echo -n " $service"
-		found=yes
-	fi
-    done
-    if [ -z "$found" ]
-    then	echo " ($service not found in $SERVICES_DIRS)"
-    fi
+    echo -n " $service"
+    service up /usr/sbin/$service "$@" 
 }
 
-get_eth_labels() {
-  # Filter out the non-vlan ethernet entries from inet.conf.
-  # Produce as output a list of "drivername_instancenr"-formatted labels.
-  sed 's/\008/ /g' /etc/inet.conf | \
-    sed -n 's/^ *eth[0-9][0-9]* *\([^ ][^ ]*\) *\([0-9][0-9]*\).*$/\1_\2/p' | \
-    grep -v '^vlan_'
-}
-
-# Detect expansion boards on the BeagleBone and load the proper drivers.
-capemgr() {
-
-    # Probe each possible cape EEPROM slave address for a BeagleBone cape.
-    for slave_addr in 54 55 56 57
-    do
-
-        # See if there is a readable EEPROM with address ${slave_addr}.
-        eepromread -f /dev/i2c-3 -a 0x${slave_addr} > /dev/null 2>&1
-        RESULT=$?
-	if [ $RESULT -eq 0 ]
-	then
-
-	    # Found an alive EEPROM. Try reading the cape name.
-            CAPE=`eepromread -i -f /dev/i2c-3 -a 0x${slave_addr} | \
-	        sed -n 's/^PART_NUMBER     : \(.*\)$/\1/p' | \
-		sed -e 's/\.*$//g'` # Strip trailing periods.
-
-	    # Look for a cape specific RC script.
-            if [ -x /etc/rc.capes/${CAPE} ]
-	    then
-
-	        # CAT24C256 EEPROM -- all capes have this chip.
-		test -e /dev/eepromb3s${slave_addr} || \
-		    (cd /dev && MAKEDEV eepromb3s${slave_addr})
-		up cat24c256 -dev /dev/eepromb3s${slave_addr} \
-		    -label cat24c256.3.${slave_addr} \
-		    -args "bus=3 address=0x${slave_addr}"
-
-                # Load the drivers for the cape and do any other configuration.
-		. "/etc/rc.capes/${CAPE}"
-
-	    else
-
-		echo ""
-	        echo "** UNSUPPORTED CAPE: ${CAPE}"
-		echo ""
-
-	    fi
-	fi
-    done
-}
 
 DAEMONS=/etc/rc.daemons
 
 case $action in
-start|autoboot)
+start)
     # Select console font.
     test -f /etc/font && loadfont /etc/font </dev/console
 
     # Cleanup.
-    rm -rf /tmp/* /usr/run/* /usr/spool/lpd/* /usr/spool/locks/*
+    rm -rf /tmp/. /usr/run/. /usr/spool/lpd/. /usr/spool/locks/.
 
     # Start servers and drivers set at the boot monitor.
     echo -n "Starting services:"
-    up -n random -dev /dev/random -period 3HZ
+    up random -dev /dev/random -period 3HZ
 
     # load random number generator
     if [ -f $RANDOM_FILE ]
@@ -180,39 +90,18 @@ start|autoboot)
     	dd if=/dev/random of=$RANDOM_FILE bs=1024 count=1 2> /dev/null
     fi
 
-    # start network driver instances for all configured ethernet devices
-    for label in $(get_eth_labels); do
-        driver=$(echo $label | sed 's/\(.*\)_.*/\1/')
-        instance=$(echo $label | sed 's/.*_//')
-        eval arg=\$${label}_arg
-        if [ ! -z "$arg" ]; then arg=" $arg"; fi
-        arg="-args \"instance=$instance$arg\""
-        eval up $driver -label $label $arg -period 5HZ
+    # start only network drivers that are in use
+    for driver in lance rtl8139 fxp dpeth dp8390
+    do
+        if grep " $driver " /etc/inet.conf > /dev/null  2>&1
+        then 
+            eval arg=\$${driver}_arg
+	    if [ ! -z "$arg" ]; then arg="-args \"$arg\""; fi
+            eval up $driver $arg -period 5HZ
+        fi
     done
-    if [ X`/bin/sysenv lwip` = Xyes ]
-    then
-	up lwip -script /etc/rs.inet -dev /dev/ip
-    else
-	up inet -script /etc/rs.inet -dev /dev/ip
-    fi
-
-    up pty -dev /dev/ptyp0
-
-    up uds -dev /dev/uds
-
-    up -n ipc
-
-    up log -dev /dev/klog
-
-    if [ $ARCH = i386 ]
-    then
-	up -n printer -dev /dev/lp -period 10HZ
-	# start VirtualBox time sync driver if the device is there
-	if grep '^[^ ]* [^ ]* 80EE:CAFE ' /proc/pci >/dev/null; then
-		up -n vbox -period 10HZ
-	fi
-    fi
-
+    up inet 
+    up printer -dev /dev/lp -period 10HZ
     echo .
 
     # Network initialization.
@@ -235,129 +124,6 @@ start|autoboot)
     daemonize syslogd
     echo .
 
-    # i2c only supported on ARM at the moment
-    if [ $ARCH = earm ]
-    then
-	echo -n "Starting i2c subsystem: "
-	for bus in 1 2 3
-	do
-		test -e /dev/i2c-${bus} || (cd /dev && MAKEDEV i2c-${bus})
-		up i2c -dev /dev/i2c-${bus} -label i2c.${bus} \
-			-args instance=${bus}
-	done
-	echo .
-
-	BOARD_NAME=`sysenv board`
-	case "${BOARD_NAME}" in
-
-		ARM-ARMV7-TI-BB-WHITE)
-			echo "Running on a BeagleBone"
-			echo -n "Starting i2c device drivers: "
-
-			# start EEPROM driver for reading board info
-			test -e /dev/eepromb1s50 || \
-				(cd /dev && MAKEDEV eepromb1s50)
-			up cat24c256 -dev /dev/eepromb1s50 \
-				-label cat24c256.1.50 \
-				-args 'bus=1 address=0x50'
-
-			# Start TPS65217 driver for power management.
-			up tps65217 -label tps65217.1.24 \
-			        -args 'bus=1 address=0x24'
-
-			# check for the presence of a display
-			eepromread -f /dev/i2c-2 -n > /dev/null 2>&1
-			RESULT=$?
-			if [ $RESULT -eq 0 ]
-			then
-				# start eeprom driver for reading EDID.
-				test -e /dev/eepromb2s50 || \
-					(cd /dev && MAKEDEV eepromb2s50)
-				up cat24c256 -dev /dev/eepromb2s50 \
-					-label cat24c256.2.50 \
-					-args 'bus=2 address=0x50'
-
-				# start frame buffer
-				#up fb -dev /dev/fb0 -args edid.0=cat24c256.2.50
-				# fb hasn't been ported to AM335X yet.
-			fi
-
-			if [ -e /service/usbd ]
-			then
-				echo "Starting USBD"
-				up usbd
-			fi
-			# Detect expansion boards and start drivers.
-			capemgr
-
-			;;
-
-		ARM-ARMV7-TI-BB-BLACK)
-			echo "Running on a BeagleBone Black"
-			echo -n "Starting i2c device drivers: "
-
-			# start EEPROM driver for reading board info
-			test -e /dev/eepromb1s50 || \
-				(cd /dev && MAKEDEV eepromb1s50)
-			up cat24c256 -dev /dev/eepromb1s50 \
-				-label cat24c256.1.50 \
-				-args 'bus=1 address=0x50'
-
-			# Start TPS65217 driver for power management.
-			up tps65217 -label tps65217.1.24 \
-			        -args 'bus=1 address=0x24'
-
-			# Start TDA19988 driver for reading EDID.
-			up tda19988 -label tda19988.1.3470 -args \
-				'cec_bus=1 cec_address=0x34 hdmi_bus=1 hdmi_address=0x70'
-
-			# start frame buffer
-			#up fb -dev /dev/fb0 -args edid.0=tda19988.1.3470
-			# fb hasn't been ported to AM335X yet.
-
-			if [ -e /service/usbd ]
-			then
-				echo "Starting USBD"
-				up usbd
-			fi
-			# Detect expansion boards and start drivers.
-			capemgr
-
-			;;
-
-		ARM-ARMV7-TI-BBXM-GENERIC)
-			echo "Running on a BeagleBoard-xM"
-			echo -n "Starting i2c device drivers: "
-
-			# Start TPS65950 driver for power management.
-			up tps65950 -label tps65950.1.48 \
-				-args 'bus=1 address=0x48'
-
-			# Set the system time to the time in the TPS65950's RTC
-			readclock
-
-			# check for the presence of a display
-			eepromread -f /dev/i2c-3 -n > /dev/null 2>&1
-			RESULT=$?
-			if [ $RESULT -eq 0 ]
-			then
-				# start eeprom driver for reading edid
-				test -e /dev/eepromb3s50 || \
-					(cd /dev && MAKEDEV eepromb3s50)
-				up cat24c256 -dev /dev/eepromb3s50 \
-					-label cat24c256.3.50 \
-					-args 'bus=3 address=0x50'
-
-				# start frame buffer
-				up fb -dev /dev/fb0 -args edid.0=cat24c256.3.50
-			fi
-
-			;;
-	esac
-
-	echo .
-    fi
-
     if [ "$net" ]
     then
 	if [ -f /etc/rc.net ]
@@ -367,16 +133,9 @@ start|autoboot)
 	else
 	    # Standard network daemons.
     	    echo -n "Starting networking:"
-	    if grep -s 'psip0.*default' /etc/inet.conf >/dev/null
+	    if grep -s 'psip0.*default' /etc/inet.conf 
 	    then	ifconfig -h 10.0.0.1
-	    else
-		    if [ X`/bin/sysenv lwip` = Xyes ]
-		    then
-			dhcpd --lwip &
-			echo -n " dhcpd"
-		    else
-			daemonize dhcpd
-		    fi
+	    else	daemonize dhcpd
 	    fi
 	    daemonize nonamed -L
 	    if [ -f "$DAEMONS" ]
@@ -391,7 +150,7 @@ start|autoboot)
     then
 	# Get the nodename from the DNS and set it.
 	trap '' 2
-	intr -t 20 hostaddr -h
+	intr -t 20 hostaddr -h || echo "Unable to obtain an IP address."
 	trap 2
     fi
 
@@ -400,10 +159,11 @@ start|autoboot)
 
     # Run the daily cleanup on systems that are not on at night.
     test -f /usr/etc/daily && sh /usr/etc/daily boot &
+
 ;;
 stop|down)
     	# Save random data, if /usr is mounted rw.
-	if grep ' \/usr .*rw.*' /etc/mtab >/dev/null
+	if grep ' \/usr .*rw' /etc/mtab >/dev/null
 	then
 	  if dd if=/dev/random of=$RANDOM_FILE.new bs=1024 count=1 2>/dev/null
     	  then
@@ -414,12 +174,10 @@ stop|down)
 	fi
 esac
 
-d=
+d=/usr/local/etc/rc.d
 # Let packages run their own scripts
-for d in /usr/local/etc/rc.d /usr/pkg/etc/rc.d
-do
-if [ -d "$d" -a -z "$bootcd" ]
-then	( if cd $d
+if [ -d "$d" ]
+then	if cd $d
 	then
 		echo -n "Local packages ($action): "
 		for f in *
@@ -431,6 +189,5 @@ then	( if cd $d
 		done
 		echo " done."
 	fi
-	)
 fi
-done
+
